<?php
declare(strict_types=1);
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CustomOption;
use Hyva\Theme\ViewModel\ProductPrice;
use Magento\Catalog\Api\Data\ProductCustomOptionInterface;
use Magento\Catalog\Block\Product\View\Options\Type\Date;
use Magento\Catalog\Pricing\Price\CustomOptionPrice;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Date $block */
/** @var ProductPrice $productPriceViewModel */
/** @var ViewModelRegistry $viewModels */
$productPriceViewModel = $viewModels->require(ProductPrice::class);
/** @var CustomOption $customOptionViewModel */
$customOptionViewModel = $viewModels->require(CustomOption::class);

$option = $block->getOption();
$optionId = $escaper->escapeHtmlAttr($option->getId());
$class = $option->getIsRequire() ? ' required' : '';
$fieldName = 'options_' . ((int) $optionId) . '_' . $option->getType();

if ($productPriceViewModel->displayPriceInclAndExclTax()) {
    $basePrice = $productPriceViewModel->getCustomOptionPriceExclTax($option, CustomOptionPrice::PRICE_CODE, $block->getProduct());
}

$htmlInputTypes = [
    ProductCustomOptionInterface::OPTION_TYPE_DATE_TIME => 'datetime-local',
    ProductCustomOptionInterface::OPTION_TYPE_DATE => 'date',
    ProductCustomOptionInterface::OPTION_TYPE_TIME => 'time',
];
?>

<div class="panth-opt-row">
    <label class="panth-opt-label"
           for="options_<?= $escaper->escapeHtmlAttr($optionId) ?>"
           x-html="updateOptionPrice('<?= $escaper->escapeJs($optionId) ?>', $el)">
        <span><?= $escaper->escapeHtml($option->getTitle()) ?></span>
        <?php if ($option->getIsRequire()): ?>
            <span class="panth-opt-required">*</span>
        <?php endif; ?>
        <span class="panth-opt-price"><?= /* @noEscape */ $block->getFormattedPrice() ?></span>
    </label>

    <div>
        <input type="<?= /* @noEscape */ $htmlInputTypes[$option->getType()] ?>"
               id="options_<?= $escaper->escapeHtmlAttr($optionId) ?>"
               x-ref="option-<?= $escaper->escapeHtmlAttr($optionId) ?>"
               name="<?= $escaper->escapeHtmlAttr($fieldName) ?>"
               <?php if ($option->getType() !== ProductCustomOptionInterface::OPTION_TYPE_TIME): ?>
                   pattern="[0-9]{2}:[0-9]{2}"
               <?php endif; ?>
               @change="
                 updateCustomOptionValue($dispatch, '<?= $escaper->escapeJs($optionId) ?>', $event.target);
                 <?php if ($option->getType() !== ProductCustomOptionInterface::OPTION_TYPE_TIME): ?>
                 const d = new Date($event.target.value)
                 <?php else: ?>
                 const d = new Date(`1999-02-10T${$event.target.value.substring(0, 5)}:00`)
                 <?php endif; ?>
                 const id = <?= (int) $optionId ?>;
                 $refs[`option-${id}-day`] && ($refs[`option-${id}-day`].value = d.getDate());
                 $refs[`option-${id}-month`] && ($refs[`option-${id}-month`].value = d.getMonth() + 1);
                 $refs[`option-${id}-year`] && ($refs[`option-${id}-year`].value = d.getFullYear());
                 $refs[`option-${id}-minute`] && ($refs[`option-${id}-minute`].value = d.getMinutes());
                 <?php if ($customOptionViewModel->is24hTimeFormat()): ?>
                 $refs[`option-${id}-hour`] && ($refs[`option-${id}-hour`].value = d.getHours());
                 <?php else: ?>
                 $refs[`option-${id}-hour`] && ($refs[`option-${id}-hour`].value = d.getHours() === 0 ? 12 : (d.getHours() > 12 ? d.getHours() - 12 : d.getHours()));
                 $refs[`option-${id}-day-part`] && ($refs[`option-${id}-day-part`].value = d.getHours() < 12 ? 'am' : 'pm');
                 <?php endif; ?>
               ">

        <?php if ($option->getType() == ProductCustomOptionInterface::OPTION_TYPE_DATE_TIME
            || $option->getType() == ProductCustomOptionInterface::OPTION_TYPE_DATE): ?>
            <input type="hidden" name="options[<?= $escaper->escapeHtmlAttr($optionId) ?>][day]" x-ref="option-<?= $escaper->escapeHtmlAttr($optionId) ?>-day">
            <input type="hidden" name="options[<?= $escaper->escapeHtmlAttr($optionId) ?>][month]" x-ref="option-<?= $escaper->escapeHtmlAttr($optionId) ?>-month">
            <input type="hidden" name="options[<?= $escaper->escapeHtmlAttr($optionId) ?>][year]" x-ref="option-<?= $escaper->escapeHtmlAttr($optionId) ?>-year">
        <?php endif; ?>

        <?php if ($option->getType() == ProductCustomOptionInterface::OPTION_TYPE_DATE_TIME
            || $option->getType() == ProductCustomOptionInterface::OPTION_TYPE_TIME): ?>
            <input type="hidden" name="options[<?= $escaper->escapeHtmlAttr($optionId) ?>][hour]" x-ref="option-<?= $escaper->escapeHtmlAttr($optionId) ?>-hour">
            <input type="hidden" name="options[<?= $escaper->escapeHtmlAttr($optionId) ?>][minute]" x-ref="option-<?= $escaper->escapeHtmlAttr($optionId) ?>-minute">
            <?php if (! $customOptionViewModel->is24hTimeFormat()): ?>
            <input type="hidden" name="options[<?= $escaper->escapeHtmlAttr($optionId) ?>][day_part]" x-ref="option-<?= $escaper->escapeHtmlAttr($optionId) ?>-day-part">
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>
