<?php
declare(strict_types=1);
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductPrice;
use Magento\Catalog\Api\Data\ProductCustomOptionInterface;
use Magento\Catalog\Block\Product\View\Options\Type\Text;
use Magento\Catalog\Model\Product\Option;
use Magento\Catalog\Pricing\Price\CustomOptionPrice;
use Magento\Framework\Escaper;

/** @var Text $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$product = $block->getProduct();
/** @var Option $option */
$option = $block->getOption();
$optionId = $option->getId();
/** @var ProductPrice $productPriceViewModel */
$productPriceViewModel = $viewModels->require(ProductPrice::class);
$optionPrice = $productPriceViewModel->getCustomOptionPrice($option, CustomOptionPrice::PRICE_CODE, $product);
if ($productPriceViewModel->displayPriceInclAndExclTax()) {
    $optionBasePrice = $productPriceViewModel->getCustomOptionPriceExclTax($option, CustomOptionPrice::PRICE_CODE, $product);
}
?>

<div class="panth-opt-row">
    <label class="panth-opt-label"
           for="options_<?= $escaper->escapeHtmlAttr($optionId) ?>_text"
           x-html="updateOptionPrice('<?= $escaper->escapeJs($optionId) ?>', $el)">
        <span><?= $escaper->escapeHtml($option->getTitle()) ?></span>
        <?php if ($option->getIsRequire()): ?>
            <span class="panth-opt-required">*</span>
        <?php endif; ?>
        <span class="panth-opt-price"><?= /* @noEscape */ $block->getFormattedPrice() ?></span>
    </label>

    <div>
        <?php if ($option->getType() == ProductCustomOptionInterface::OPTION_TYPE_FIELD): ?>
            <input type="text"
                   id="options_<?= $escaper->escapeHtmlAttr($optionId) ?>_text"
                   class="product-custom-option"
                   name="options[<?= $escaper->escapeHtmlAttr($optionId) ?>]"
                   value="<?= $escaper->escapeHtml($block->getDefaultValue()) ?>"
                   placeholder="<?= $escaper->escapeHtmlAttr(__('Enter %1', $option->getTitle())) ?>"
                   <?php if ($option->getMaxCharacters()): ?>maxlength="<?= (int)$option->getMaxCharacters() ?>"<?php endif; ?>
                   <?= $option->getIsRequire() ? 'required' : '' ?>
                   data-price-amount="<?= $escaper->escapeHtmlAttr($optionPrice) ?>"
                   data-price-type="<?= $escaper->escapeHtmlAttr($option->getPriceType()) ?>"
                   data-option-id="<?= $escaper->escapeHtmlAttr($optionId) ?>"
                   x-ref="option-<?= $escaper->escapeHtmlAttr($optionId) ?>"
                   x-on:input="updateCustomOptionValue($dispatch, '<?= $escaper->escapeHtmlAttr($optionId) ?>', $event.target)">
        <?php elseif ($option->getType() == ProductCustomOptionInterface::OPTION_TYPE_AREA): ?>
            <textarea id="options_<?= $escaper->escapeHtmlAttr($optionId) ?>_text"
                      class="product-custom-option"
                      name="options[<?= $escaper->escapeHtmlAttr($optionId) ?>]"
                      placeholder="<?= $escaper->escapeHtmlAttr(__('Enter %1', $option->getTitle())) ?>"
                      <?php if ($option->getMaxCharacters()): ?>maxlength="<?= (int)$option->getMaxCharacters() ?>"<?php endif; ?>
                      <?= $option->getIsRequire() ? 'required' : '' ?>
                      rows="4"
                      data-price-amount="<?= $escaper->escapeHtmlAttr($optionPrice) ?>"
                      data-price-type="<?= $escaper->escapeHtmlAttr($option->getPriceType()) ?>"
                      data-option-id="<?= $escaper->escapeHtmlAttr($optionId) ?>"
                      x-ref="option-<?= $escaper->escapeHtmlAttr($optionId) ?>"
                      x-on:input="updateCustomOptionValue($dispatch, '<?= $escaper->escapeHtmlAttr($optionId) ?>', $event.target)"
            ><?= $escaper->escapeHtml($block->getDefaultValue()) ?></textarea>
        <?php endif; ?>
        <?php if ($option->getMaxCharacters()): ?>
            <p class="panth-opt-note"><?= $escaper->escapeHtml(__('Maximum %1 characters', $option->getMaxCharacters())) ?></p>
        <?php endif; ?>
    </div>
</div>
